# Generated by Django 3.0.7 on 2020-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='teacher',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
