# Generated by Django 3.0.7 on 2020-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_assignments_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='branch',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Electronics', 'Electronics')], default='Computer Science', max_length=30),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='status',
            field=models.CharField(choices=[('checked', 'checked'), ('unchecked', 'unchecked')], default='unchecked', max_length=15),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='uploadingdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='uploadingtime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Electronics', 'Electronics')], default='Computer Science', max_length=30),
        ),
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='branch',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Electronics', 'Electronics')], default='Computer Science', max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=15),
        ),
    ]
